- mode: 		# 'image' or 'video' mode.
  images_path: 		# The path to the directory with images in the 'image' mode.
  video_path: 		# The path to the directory with video in the 'video' mode.
  groundtruth_path: 	# The path to the layout in the csv format, if it is available.
  model_name: 		# The model name
  adapter_name: 	# Adapter name for the model
  path_classes: 	# The path to the file with the names of the classes for which the model was trained
  path_weights: 	# The path to the model weights file
  path_config: 		# The path to the model description file
  path_anchors:
  write_path: 		# The path to the output file with detections
  batch_size:		# The batch size for inference
  confidence: 		# Desired detection accuracy
  nms_threshold: 	# Desired overlap area for non-maximal suppression (in [0, 1])
  scale: 		# Scale factor to normalize pixel intencities (in [0, 1])
  size: 		# The input size of the model
  mean: 		# The mean value of intencities for each channel (three values in [0, 255])
  swapRB: 		# Flag to swap red and blue channels. The value is False or True
  silent_mode: 		# Flag that correspond to the application mode (GUI or console). The value is True (console) or False (GUI)
